name: Bug report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Errors
      render: shell

  - type: input
    id: version
    attributes:
      label: Python Version
      placeholder: "3.12"

  - type: dropdown
    id: contribute
    attributes:
      label: Are you willing to submit a PR to fix this?
      options:
        - "Yes"
        - "No"

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and discussions for duplicates
          required: true
