name: Feature request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, mockups, references, etc.

  - type: dropdown
    id: contribute
    attributes:
      label: Are you willing to submit a PR for this?
      options:
        - "Yes"
        - "No"
        - "Maybe (need guidance)"

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and discussions for duplicates
          required: true
