name: Security vulnerability
description: Report a security issue (please use responsibly)
title: "[SECURITY] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **For critical vulnerabilities**, please email security@xyber.io instead of creating a public issue.

        Use this form only for non-critical security concerns or questions.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low - Minor security improvement
        - Medium - Potential vulnerability
        - High - Confirmed vulnerability (use email instead)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if exploited?

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we verify this issue?

  - type: dropdown
    id: contribute
    attributes:
      label: Are you willing to submit a PR to fix this?
      options:
        - "Yes"
        - "No"
        - "Maybe (need guidance)"

  - type: checkboxes
    id: terms
    attributes:
      label: Responsible Disclosure
      options:
        - label: I have not disclosed this vulnerability publicly
          required: true
        - label: I agree to coordinate disclosure with the maintainers
          required: true
